// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOAuthProvider = `-- name: DeleteOAuthProvider :exec
DELETE FROM oauth_providers WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthProviderParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) DeleteOAuthProvider(ctx context.Context, arg DeleteOAuthProviderParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthProvider = `-- name: GetOAuthProvider :one
SELECT provider, provider_id, user_id, email, created_at FROM oauth_providers
WHERE provider = $1 AND provider_id = $2
`

type GetOAuthProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthProvider(ctx context.Context, arg GetOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProvider, arg.Provider, arg.ProviderID)
	var i OauthProvider
	err := row.Scan(
		&i.Provider,
		&i.ProviderID,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthProvidersByUserID = `-- name: GetOAuthProvidersByUserID :many
SELECT provider, provider_id, user_id, email, created_at FROM oauth_providers WHERE user_id = $1
`

func (q *Queries) GetOAuthProvidersByUserID(ctx context.Context, userID pgtype.UUID) ([]OauthProvider, error) {
	rows, err := q.db.Query(ctx, getOAuthProvidersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthProvider
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.Provider,
			&i.ProviderID,
			&i.UserID,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOAuthProvider = `-- name: InsertOAuthProvider :exec
INSERT INTO oauth_providers (provider, provider_id, user_id, email)
VALUES ($1, $2, $3, $4)
`

type InsertOAuthProviderParams struct {
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Email      string      `json:"email"`
}

func (q *Queries) InsertOAuthProvider(ctx context.Context, arg InsertOAuthProviderParams) error {
	_, err := q.db.Exec(ctx, insertOAuthProvider,
		arg.Provider,
		arg.ProviderID,
		arg.UserID,
		arg.Email,
	)
	return err
}
