// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abortVolumeDelete = `-- name: AbortVolumeDelete :exec
UPDATE volumes
SET status       = 'detached',
    last_updated = NOW()
WHERE id = $1 AND status = 'deleting'
`

// Revert a delete claim back to detached when the host-side file removal fails,
// so the volume stays usable rather than stuck in 'deleting'.
func (q *Queries) AbortVolumeDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, abortVolumeDelete, id)
	return err
}

const beginVolumeDelete = `-- name: BeginVolumeDelete :one
UPDATE volumes
SET status       = 'deleting',
    last_updated = NOW()
WHERE id = $1 AND team_id = $2 AND status IN ('detached', 'deleting')
RETURNING id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated
`

type BeginVolumeDeleteParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

// Atomically claim a volume for deletion. The CAS blocks a concurrent attach
// (which needs status='detached') so a volume can never be attached and deleted
// at the same time. 'deleting' is also accepted so a delete that crashed
// mid-flight can be retried rather than leaving the volume permanently stuck.
// Returns the row (for host_id) when claimed; no row means it is not deletable
// (attached/attaching, wrong team, or missing).
func (q *Queries) BeginVolumeDelete(ctx context.Context, arg BeginVolumeDeleteParams) (Volume, error) {
	row := q.db.QueryRow(ctx, beginVolumeDelete, arg.ID, arg.TeamID)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}

const countVolumesByHost = `-- name: CountVolumesByHost :one
SELECT COUNT(*) FROM volumes WHERE host_id = $1
`

// Guard used before a host can be removed: a host holding pinned volumes must
// not be deleted out from under them.
func (q *Queries) CountVolumesByHost(ctx context.Context, hostID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVolumesByHost, hostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVolumeRow = `-- name: DeleteVolumeRow :exec
DELETE FROM volumes WHERE id = $1 AND team_id = $2
`

type DeleteVolumeRowParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteVolumeRow(ctx context.Context, arg DeleteVolumeRowParams) error {
	_, err := q.db.Exec(ctx, deleteVolumeRow, arg.ID, arg.TeamID)
	return err
}

const detachVolumesByHost = `-- name: DetachVolumesByHost :exec
UPDATE volumes
SET status       = 'detached',
    sandbox_id   = NULL,
    host_id      = NULL,
    mount_path   = '',
    last_updated = NOW()
WHERE host_id = $1
`

// Free and un-pin every volume on a host being force-deleted. The host (and its
// backing files) are going away, so the volumes are reset to a fresh detached,
// un-pinned state — the rows survive (never auto-deleted) and can be re-attached
// on a new host. Also required before DeleteHost so the host_id FK does not
// block deletion.
func (q *Queries) DetachVolumesByHost(ctx context.Context, hostID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, detachVolumesByHost, hostID)
	return err
}

const detachVolumesBySandbox = `-- name: DetachVolumesBySandbox :exec
UPDATE volumes
SET status       = 'detached',
    sandbox_id   = NULL,
    mount_path   = '',
    last_updated = NOW()
WHERE sandbox_id = $1 AND status = 'attached'
`

// Terminal sweep run when a capsule reaches a terminal state (destroyed,
// stopped, errored, or reaped): free every volume it held back to detached
// (data and host pin preserved) so it can be reused or deleted. Keyed on
// sandbox_id, which is set at attach time. Never deletes the volume — removal
// is always explicit.
func (q *Queries) DetachVolumesBySandbox(ctx context.Context, sandboxID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, detachVolumesBySandbox, sandboxID)
	return err
}

const detachVolumesBySandboxIDs = `-- name: DetachVolumesBySandboxIDs :exec
UPDATE volumes
SET status       = 'detached',
    sandbox_id   = NULL,
    mount_path   = '',
    last_updated = NOW()
WHERE sandbox_id = ANY($1::uuid[]) AND status = 'attached'
`

// Bulk variant of DetachVolumesBySandbox for the host monitor, which stops
// many sandboxes at once (e.g. after a host goes offline).
func (q *Queries) DetachVolumesBySandboxIDs(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, detachVolumesBySandboxIDs, dollar_1)
	return err
}

const getVolume = `-- name: GetVolume :one
SELECT id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated FROM volumes WHERE id = $1
`

func (q *Queries) GetVolume(ctx context.Context, id pgtype.UUID) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolume, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}

const getVolumeByTeam = `-- name: GetVolumeByTeam :one
SELECT id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated FROM volumes WHERE id = $1 AND team_id = $2
`

type GetVolumeByTeamParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) GetVolumeByTeam(ctx context.Context, arg GetVolumeByTeamParams) (Volume, error) {
	row := q.db.QueryRow(ctx, getVolumeByTeam, arg.ID, arg.TeamID)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}

const insertVolume = `-- name: InsertVolume :one
INSERT INTO volumes (id, team_id, name, size_mb, status)
VALUES ($1, $2, $3, $4, 'detached')
RETURNING id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated
`

type InsertVolumeParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
	Name   string      `json:"name"`
	SizeMb int32       `json:"size_mb"`
}

func (q *Queries) InsertVolume(ctx context.Context, arg InsertVolumeParams) (Volume, error) {
	row := q.db.QueryRow(ctx, insertVolume,
		arg.ID,
		arg.TeamID,
		arg.Name,
		arg.SizeMb,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}

const listVolumesBySandbox = `-- name: ListVolumesBySandbox :many
SELECT id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated FROM volumes WHERE sandbox_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVolumesBySandbox(ctx context.Context, sandboxID pgtype.UUID) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesBySandbox, sandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.HostID,
			&i.Name,
			&i.SizeMb,
			&i.Status,
			&i.SandboxID,
			&i.MountPath,
			&i.CreatedAt,
			&i.LastAttachedAt,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByTeam = `-- name: ListVolumesByTeam :many
SELECT id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated FROM volumes WHERE team_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListVolumesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Volume, error) {
	rows, err := q.db.Query(ctx, listVolumesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.HostID,
			&i.Name,
			&i.SizeMb,
			&i.Status,
			&i.SandboxID,
			&i.MountPath,
			&i.CreatedAt,
			&i.LastAttachedAt,
			&i.LastUpdated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVolumeAttached = `-- name: MarkVolumeAttached :one
UPDATE volumes
SET status           = 'attached',
    host_id          = COALESCE(host_id, $2),
    sandbox_id       = $3,
    mount_path       = $4,
    last_attached_at = NOW(),
    last_updated     = NOW()
WHERE id = $1 AND status = 'attaching'
RETURNING id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated
`

type MarkVolumeAttachedParams struct {
	ID        pgtype.UUID `json:"id"`
	HostID    pgtype.UUID `json:"host_id"`
	SandboxID pgtype.UUID `json:"sandbox_id"`
	MountPath string      `json:"mount_path"`
}

// Promote a reserved volume to attached once the capsule has booted with it.
// Records the owning sandbox and pins the volume to the sandbox's host on
// first-ever attach (COALESCE keeps an existing pin for a re-attached volume).
func (q *Queries) MarkVolumeAttached(ctx context.Context, arg MarkVolumeAttachedParams) (Volume, error) {
	row := q.db.QueryRow(ctx, markVolumeAttached,
		arg.ID,
		arg.HostID,
		arg.SandboxID,
		arg.MountPath,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}

const releaseStaleVolumeReservations = `-- name: ReleaseStaleVolumeReservations :execrows
UPDATE volumes
SET status       = 'detached',
    sandbox_id   = NULL,
    mount_path   = '',
    last_updated = NOW()
WHERE status IN ('attaching', 'deleting') AND last_updated < $1
`

// Free volumes stuck in a transient state (attaching/deleting) whose owning
// operation died — e.g. the control plane crashed between reserving a volume
// and the capsule booting, or mid-delete. Run periodically by the volume reaper.
// The cutoff ($1 = now - grace) MUST exceed the capsule create timeout so a
// legitimately in-flight attach is never freed out from under a booting capsule.
func (q *Queries) ReleaseStaleVolumeReservations(ctx context.Context, lastUpdated pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStaleVolumeReservations, lastUpdated)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseVolumeReservation = `-- name: ReleaseVolumeReservation :exec
UPDATE volumes
SET status       = 'detached',
    sandbox_id   = NULL,
    last_updated = NOW()
WHERE id = $1 AND status = 'attaching'
`

// Roll a reserved volume back to detached when the capsule create fails.
// host_id is left untouched (a failed create never pins a fresh volume, since
// MarkVolumeAttached is what sets the pin).
func (q *Queries) ReleaseVolumeReservation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseVolumeReservation, id)
	return err
}

const reserveVolumeForAttach = `-- name: ReserveVolumeForAttach :one
UPDATE volumes
SET status       = 'attaching',
    last_updated = NOW()
WHERE id = $1 AND status = 'detached'
RETURNING id, team_id, host_id, name, size_mb, status, sandbox_id, mount_path, created_at, last_attached_at, last_updated
`

// Atomically claim a detached volume for a capsule about to boot. The CAS on
// status = 'detached' enforces single-attach: a second capsule create racing
// for the same volume finds no row and fails. sandbox_id is deliberately NOT
// set here — the sandbox row does not exist yet, so setting the FK would fail.
// It is set in MarkVolumeAttached once the capsule has booted.
func (q *Queries) ReserveVolumeForAttach(ctx context.Context, id pgtype.UUID) (Volume, error) {
	row := q.db.QueryRow(ctx, reserveVolumeForAttach, id)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.HostID,
		&i.Name,
		&i.SizeMb,
		&i.Status,
		&i.SandboxID,
		&i.MountPath,
		&i.CreatedAt,
		&i.LastAttachedAt,
		&i.LastUpdated,
	)
	return i, err
}
