package validate

import "testing"

func TestTeamSlug(t *testing.T) {
	tests := []struct {
		name    string
		slug    string
		wantErr bool
	}{
		{"autogenerated form", "a1b2c3-d4e5f6", false},
		{"simple", "acme", false},
		{"with dashes", "acme-corp-labs", false},
		{"digits", "team123", false},
		{"min length", "abc", false},
		{"empty", "", true},
		{"too short", "ab", true},
		{"too long", "this-slug-is-definitely-way-too-long-to-be-valid", true},
		{"uppercase", "Acme", true},
		{"leading dash", "-acme", true},
		{"trailing dash", "acme-", true},
		{"double dash", "acme--corp", true},
		{"slash", "acme/corp", true},
		{"dot", "acme.corp", true},
		{"space", "acme corp", true},
		{"reserved platform", "platform", true},
		{"reserved wrenn", "wrenn", true},
		{"reserved zero", "0", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := TeamSlug(tt.slug)
			if (err != nil) != tt.wantErr {
				t.Errorf("TeamSlug(%q) error = %v, wantErr %v", tt.slug, err, tt.wantErr)
			}
		})
	}
}

func TestTemplateRef(t *testing.T) {
	tests := []struct {
		name     string
		ref      string
		wantSlug string
		wantName string
		wantErr  bool
	}{
		{"bare name", "minimal-ubuntu", "", "minimal-ubuntu", false},
		{"slug qualified", "acme/devbox", "acme", "devbox", false},
		{"platform qualified", "platform/minimal-ubuntu", "platform", "minimal-ubuntu", false},
		{"trims space", "  acme/devbox  ", "acme", "devbox", false},
		{"empty", "", "", "", true},
		{"two slashes", "acme/team/devbox", "", "", true},
		{"trailing slash", "acme/", "", "", true},
		{"leading slash", "/devbox", "", "", true},
		{"bad slug", "Acme/devbox", "", "", true},
		{"bad name", "acme/bad name", "", "", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			slug, name, err := TemplateRef(tt.ref)
			if (err != nil) != tt.wantErr {
				t.Fatalf("TemplateRef(%q) error = %v, wantErr %v", tt.ref, err, tt.wantErr)
			}
			if tt.wantErr {
				return
			}
			if slug != tt.wantSlug || name != tt.wantName {
				t.Errorf("TemplateRef(%q) = (%q, %q), want (%q, %q)", tt.ref, slug, name, tt.wantSlug, tt.wantName)
			}
		})
	}
}
