// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Sandbox struct {
	ID           string             `json:"id"`
	OwnerID      string             `json:"owner_id"`
	HostID       string             `json:"host_id"`
	Template     string             `json:"template"`
	Status       string             `json:"status"`
	Vcpus        int32              `json:"vcpus"`
	MemoryMb     int32              `json:"memory_mb"`
	TimeoutSec   int32              `json:"timeout_sec"`
	GuestIp      string             `json:"guest_ip"`
	HostIp       string             `json:"host_ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	LastUpdated  pgtype.Timestamptz `json:"last_updated"`
}

type Template struct {
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Vcpus     pgtype.Int4        `json:"vcpus"`
	MemoryMb  pgtype.Int4        `json:"memory_mb"`
	SizeBytes int64              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
