// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"
)

const getOAuthProvider = `-- name: GetOAuthProvider :one
SELECT provider, provider_id, user_id, email, created_at FROM oauth_providers
WHERE provider = $1 AND provider_id = $2
`

type GetOAuthProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthProvider(ctx context.Context, arg GetOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProvider, arg.Provider, arg.ProviderID)
	var i OauthProvider
	err := row.Scan(
		&i.Provider,
		&i.ProviderID,
		&i.UserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const insertOAuthProvider = `-- name: InsertOAuthProvider :exec
INSERT INTO oauth_providers (provider, provider_id, user_id, email)
VALUES ($1, $2, $3, $4)
`

type InsertOAuthProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
	UserID     string `json:"user_id"`
	Email      string `json:"email"`
}

func (q *Queries) InsertOAuthProvider(ctx context.Context, arg InsertOAuthProviderParams) error {
	_, err := q.db.Exec(ctx, insertOAuthProvider,
		arg.Provider,
		arg.ProviderID,
		arg.UserID,
		arg.Email,
	)
	return err
}
