// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE name = $1
`

func (q *Queries) DeleteTemplate(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteTemplate, name)
	return err
}

const deleteTemplateByTeam = `-- name: DeleteTemplateByTeam :exec
DELETE FROM templates WHERE name = $1 AND team_id = $2
`

type DeleteTemplateByTeamParams struct {
	Name   string      `json:"name"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) DeleteTemplateByTeam(ctx context.Context, arg DeleteTemplateByTeamParams) error {
	_, err := q.db.Exec(ctx, deleteTemplateByTeam, arg.Name, arg.TeamID)
	return err
}

const getTemplate = `-- name: GetTemplate :one
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates WHERE name = $1
`

func (q *Queries) GetTemplate(ctx context.Context, name string) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplate, name)
	var i Template
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Vcpus,
		&i.MemoryMb,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const getTemplateByTeam = `-- name: GetTemplateByTeam :one
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates WHERE name = $1 AND (team_id = $2 OR team_id = '00000000-0000-0000-0000-000000000000')
`

type GetTemplateByTeamParams struct {
	Name   string      `json:"name"`
	TeamID pgtype.UUID `json:"team_id"`
}

// Platform templates (team_id = 00000000-...) are visible to all teams.
func (q *Queries) GetTemplateByTeam(ctx context.Context, arg GetTemplateByTeamParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByTeam, arg.Name, arg.TeamID)
	var i Template
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Vcpus,
		&i.MemoryMb,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const insertTemplate = `-- name: InsertTemplate :one
INSERT INTO templates (name, type, vcpus, memory_mb, size_bytes, team_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING name, type, vcpus, memory_mb, size_bytes, created_at, team_id
`

type InsertTemplateParams struct {
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Vcpus     int32       `json:"vcpus"`
	MemoryMb  int32       `json:"memory_mb"`
	SizeBytes int64       `json:"size_bytes"`
	TeamID    pgtype.UUID `json:"team_id"`
}

func (q *Queries) InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, insertTemplate,
		arg.Name,
		arg.Type,
		arg.Vcpus,
		arg.MemoryMb,
		arg.SizeBytes,
		arg.TeamID,
	)
	var i Template
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Vcpus,
		&i.MemoryMb,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.TeamID,
	)
	return i, err
}

const listTemplates = `-- name: ListTemplates :many
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates ORDER BY created_at DESC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Vcpus,
			&i.MemoryMb,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByTeam = `-- name: ListTemplatesByTeam :many
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates WHERE (team_id = $1 OR team_id = '00000000-0000-0000-0000-000000000000') ORDER BY created_at DESC
`

// Platform templates are visible to all teams.
func (q *Queries) ListTemplatesByTeam(ctx context.Context, teamID pgtype.UUID) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Vcpus,
			&i.MemoryMb,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByTeamAndType = `-- name: ListTemplatesByTeamAndType :many
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates WHERE (team_id = $1 OR team_id = '00000000-0000-0000-0000-000000000000') AND type = $2 ORDER BY created_at DESC
`

type ListTemplatesByTeamAndTypeParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	Type   string      `json:"type"`
}

// Platform templates are visible to all teams.
func (q *Queries) ListTemplatesByTeamAndType(ctx context.Context, arg ListTemplatesByTeamAndTypeParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTeamAndType, arg.TeamID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Vcpus,
			&i.MemoryMb,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByType = `-- name: ListTemplatesByType :many
SELECT name, type, vcpus, memory_mb, size_bytes, created_at, team_id FROM templates WHERE type = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTemplatesByType(ctx context.Context, type_ string) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Vcpus,
			&i.MemoryMb,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
